version: '3'
    
services:
  dynamodb-local:
    container_name: dynamodb-local
    build: dynamodb-local
    ports:
      - "8000:8000"
    networks: 
      - backend

  backend:
    image: adamgatt/webdungeon_backend:latest
    container_name: backend 
    build: backend
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - dynamodb-local
    networks:
      - backend

networks:
  backend:
