version: '3'
    
services:
  db:
    container_name: dynamodb-local
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    networks: 
      - backend

  backend:
    container_name: backend 
    build: backend
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
