name: Deploy to AWS on push to master
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: aws_deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: |
          docker build -t adamgatt/cloud_backend -f ./backend/Dockerfile backend

      - name: Push image to DockerHub
        run: |
          # Set up docker credentials and then push the built image
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push adamgatt/cloud_backend
          docker logout # Remove credentials after pushing to dockerhub
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: cloud-backend
          template: ./cloudformation_ec2.yml